apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasks-pvc
  namespace: odoo
spec:
  storageClassName: "sc-tasks-pvc" ## IMPORTANT - this enables auto PV creating
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi