apiVersion: v1
kind: Namespace
metadata:
  name: game
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
  namespace: game
spec:
  selector:
    matchLabels: 
      name: game-2048
  replicas: 3
  template:
    metadata:
      labels: 
        name: game-2048
    spec:
      containers:
      - name: app
        image: k8smaestro/2048
        imagePullPolicy: Always # When new image with same tags containers always download new image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: game
  name: service-2048
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    name: game-2048