apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-app
  namespace: odoo
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: odoo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - name: odoo
          image: docker.io/bitnami/odoo:16
          ports:
            - containerPort: 8069
          env:
            - name: ODOO_DATABASE_HOST
              value: "postgresql.odoo.svc.cluster.local"
            - name: ODOO_DATABASE_PORT_NUMBER
              value: "5432"
            - name: ODOO_DATABASE_USER
              value: "odoo"
            - name: ODOO_DATABASE_NAME
              value: "k8smaestro"
            - name: ODOO_DATABASE_PASSWORD
              value: "k8smaestro"
            - name: ODOO_EMAIL
              value: "kacper@cos.com"
            - name: ODOO_PASSWORD
              value: "bombel"
          resources:
            requests:
              cpu: 100m
              memory: 220Mi
            limits:
              cpu: 200m
              memory: 450Mi
          volumeMounts:
            - name: tasksvol
              mountPath: /bitnami/odoo
      volumes:
        - name: tasksvol
          persistentVolumeClaim:
            claimName: tasks-pvc