apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-tasks-pvc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" # setting this StorageClass as default for all PV in the cluster
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer # will be created when the first client agrees with the demand for space
parameters: ## parameters specific for GCP
  type: pd-standard
  fstype: ext4
  replication-type: none