apiVersion: v1
kind: Namespace
metadata:
  name: k8s-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-k8s
  namespace: k8s-namespace
spec:
  selector:
    matchLabels:
      name: k8s
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: k8s
    spec:
      containers:
      - name: webapp
        image: k8smaestro/web-app:2.0