---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-view
roleRef:
  kind: ClusterRole
  name: view # Access Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: pod-reader-sa # Define for who you give permission
  namespace: pod-reader